// <auto-generated />
namespace ST.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class a6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(a6));
        
        string IMigrationMetadata.Id
        {
            get { return "201708181029273_a6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
